import type { AssociationRateTableSet } from '../types';

export const ASSOCIATION_RATE_TABLE_2019_04: AssociationRateTableSet = {
  effectiveFrom: '2019-04-01',
  label: '平成31年度 協会けんぽ',
  careInsuranceRate: 0.0173,
  pensionInsuranceRate: 0.18300,
  prefectures: [
    { prefectureCode: '01', prefectureName: '北海道', healthInsuranceRate: 0.10180 },
    { prefectureCode: '02', prefectureName: '青森県', healthInsuranceRate: 0.09880 },
    { prefectureCode: '03', prefectureName: '岩手県', healthInsuranceRate: 0.09850 },
    { prefectureCode: '04', prefectureName: '宮城県', healthInsuranceRate: 0.09810 },
    { prefectureCode: '05', prefectureName: '秋田県', healthInsuranceRate: 0.10100 },
    { prefectureCode: '06', prefectureName: '山形県', healthInsuranceRate: 0.09910 },
    { prefectureCode: '07', prefectureName: '福島県', healthInsuranceRate: 0.09830 },
    { prefectureCode: '08', prefectureName: '茨城県', healthInsuranceRate: 0.09840 },
    { prefectureCode: '09', prefectureName: '栃木県', healthInsuranceRate: 0.09860 },
    { prefectureCode: '10', prefectureName: '群馬県', healthInsuranceRate: 0.09800 },
    { prefectureCode: '11', prefectureName: '埼玉県', healthInsuranceRate: 0.09830 },
    { prefectureCode: '12', prefectureName: '千葉県', healthInsuranceRate: 0.09850 },
    { prefectureCode: '13', prefectureName: '東京都', healthInsuranceRate: 0.09900 },
    { prefectureCode: '14', prefectureName: '神奈川県', healthInsuranceRate: 0.09870 },
    { prefectureCode: '15', prefectureName: '新潟県', healthInsuranceRate: 0.09740 },
    { prefectureCode: '16', prefectureName: '富山県', healthInsuranceRate: 0.09740 },
    { prefectureCode: '17', prefectureName: '石川県', healthInsuranceRate: 0.09860 },
    { prefectureCode: '18', prefectureName: '福井県', healthInsuranceRate: 0.09930 },
    { prefectureCode: '19', prefectureName: '山梨県', healthInsuranceRate: 0.09840 },
    { prefectureCode: '20', prefectureName: '長野県', healthInsuranceRate: 0.09680 },
    { prefectureCode: '21', prefectureName: '岐阜県', healthInsuranceRate: 0.09860 },
    { prefectureCode: '22', prefectureName: '静岡県', healthInsuranceRate: 0.09750 },
    { prefectureCode: '23', prefectureName: '愛知県', healthInsuranceRate: 0.09880 },
    { prefectureCode: '24', prefectureName: '三重県', healthInsuranceRate: 0.09840 },
    { prefectureCode: '25', prefectureName: '滋賀県', healthInsuranceRate: 0.09850 },
    { prefectureCode: '26', prefectureName: '京都府', healthInsuranceRate: 0.09990 },
    { prefectureCode: '27', prefectureName: '大阪府', healthInsuranceRate: 0.10170 },
    { prefectureCode: '28', prefectureName: '兵庫県', healthInsuranceRate: 0.10110 },
    { prefectureCode: '29', prefectureName: '奈良県', healthInsuranceRate: 0.10090 },
    { prefectureCode: '30', prefectureName: '和歌山県', healthInsuranceRate: 0.10070 },
    { prefectureCode: '31', prefectureName: '鳥取県', healthInsuranceRate: 0.10000 },
    { prefectureCode: '32', prefectureName: '島根県', healthInsuranceRate: 0.10040 },
    { prefectureCode: '33', prefectureName: '岡山県', healthInsuranceRate: 0.10120 },
    { prefectureCode: '34', prefectureName: '広島県', healthInsuranceRate: 0.10000 },
    { prefectureCode: '35', prefectureName: '山口県', healthInsuranceRate: 0.10070 },
    { prefectureCode: '36', prefectureName: '徳島県', healthInsuranceRate: 0.10190 },
    { prefectureCode: '37', prefectureName: '香川県', healthInsuranceRate: 0.10130 },
    { prefectureCode: '38', prefectureName: '愛媛県', healthInsuranceRate: 0.10000 },
    { prefectureCode: '39', prefectureName: '高知県', healthInsuranceRate: 0.10180 },
    { prefectureCode: '40', prefectureName: '福岡県', healthInsuranceRate: 0.10210 },
    { prefectureCode: '41', prefectureName: '佐賀県', healthInsuranceRate: 0.10750 },
    { prefectureCode: '42', prefectureName: '長崎県', healthInsuranceRate: 0.10150 },
    { prefectureCode: '43', prefectureName: '熊本県', healthInsuranceRate: 0.10210 },
    { prefectureCode: '44', prefectureName: '大分県', healthInsuranceRate: 0.10220 },
    { prefectureCode: '45', prefectureName: '宮崎県', healthInsuranceRate: 0.09990 },
    { prefectureCode: '46', prefectureName: '鹿児島県', healthInsuranceRate: 0.10140 },
    { prefectureCode: '47', prefectureName: '沖縄県', healthInsuranceRate: 0.09930 },
  ],
};