import type { AssociationRateTableSet } from '../types';

export const ASSOCIATION_RATE_TABLE_2026_03 = {
  effectiveFrom: '2026-03-01',
  label: '令和8年度 協会けんぽ',
  careInsuranceRate: 0.0162,
  pensionInsuranceRate: 0.183,
  prefectures: [
    { prefectureCode: '01', prefectureName: '北海道', healthInsuranceRate: 0.1028 },
    { prefectureCode: '02', prefectureName: '青森県', healthInsuranceRate: 0.0985 },
    { prefectureCode: '03', prefectureName: '岩手県', healthInsuranceRate: 0.0951 },
    { prefectureCode: '04', prefectureName: '宮城県', healthInsuranceRate: 0.1010 },
    { prefectureCode: '05', prefectureName: '秋田県', healthInsuranceRate: 0.1001 },
    { prefectureCode: '06', prefectureName: '山形県', healthInsuranceRate: 0.0975 },
    { prefectureCode: '07', prefectureName: '福島県', healthInsuranceRate: 0.0950 },
    { prefectureCode: '08', prefectureName: '茨城県', healthInsuranceRate: 0.0952 },
    { prefectureCode: '09', prefectureName: '栃木県', healthInsuranceRate: 0.0982 },
    { prefectureCode: '10', prefectureName: '群馬県', healthInsuranceRate: 0.0968 },
    { prefectureCode: '11', prefectureName: '埼玉県', healthInsuranceRate: 0.0967 },
    { prefectureCode: '12', prefectureName: '千葉県', healthInsuranceRate: 0.0973 },
    { prefectureCode: '13', prefectureName: '東京都', healthInsuranceRate: 0.0985 },
    { prefectureCode: '14', prefectureName: '神奈川県', healthInsuranceRate: 0.0992 },
    { prefectureCode: '15', prefectureName: '新潟県', healthInsuranceRate: 0.0921 },
    { prefectureCode: '16', prefectureName: '富山県', healthInsuranceRate: 0.0959 },
    { prefectureCode: '17', prefectureName: '石川県', healthInsuranceRate: 0.0970 },
    { prefectureCode: '18', prefectureName: '福井県', healthInsuranceRate: 0.0971 },
    { prefectureCode: '19', prefectureName: '山梨県', healthInsuranceRate: 0.0955 },
    { prefectureCode: '20', prefectureName: '長野県', healthInsuranceRate: 0.0963 },
    { prefectureCode: '21', prefectureName: '岐阜県', healthInsuranceRate: 0.0980 },
    { prefectureCode: '22', prefectureName: '静岡県', healthInsuranceRate: 0.0961 },
    { prefectureCode: '23', prefectureName: '愛知県', healthInsuranceRate: 0.0993 },
    { prefectureCode: '24', prefectureName: '三重県', healthInsuranceRate: 0.0977 },
    { prefectureCode: '25', prefectureName: '滋賀県', healthInsuranceRate: 0.0988 },
    { prefectureCode: '26', prefectureName: '京都府', healthInsuranceRate: 0.0989 },
    { prefectureCode: '27', prefectureName: '大阪府', healthInsuranceRate: 0.1013 },
    { prefectureCode: '28', prefectureName: '兵庫県', healthInsuranceRate: 0.1012 },
    { prefectureCode: '29', prefectureName: '奈良県', healthInsuranceRate: 0.0991 },
    { prefectureCode: '30', prefectureName: '和歌山県', healthInsuranceRate: 0.1006 },
    { prefectureCode: '31', prefectureName: '鳥取県', healthInsuranceRate: 0.0986 },
    { prefectureCode: '32', prefectureName: '島根県', healthInsuranceRate: 0.0994 },
    { prefectureCode: '33', prefectureName: '岡山県', healthInsuranceRate: 0.1005 },
    { prefectureCode: '34', prefectureName: '広島県', healthInsuranceRate: 0.0978 },
    { prefectureCode: '35', prefectureName: '山口県', healthInsuranceRate: 0.1015 },
    { prefectureCode: '36', prefectureName: '徳島県', healthInsuranceRate: 0.1024 },
    { prefectureCode: '37', prefectureName: '香川県', healthInsuranceRate: 0.1002 },
    { prefectureCode: '38', prefectureName: '愛媛県', healthInsuranceRate: 0.0998 },
    { prefectureCode: '39', prefectureName: '高知県', healthInsuranceRate: 0.1005 },
    { prefectureCode: '40', prefectureName: '福岡県', healthInsuranceRate: 0.1011 },
    { prefectureCode: '41', prefectureName: '佐賀県', healthInsuranceRate: 0.1055 },
    { prefectureCode: '42', prefectureName: '長崎県', healthInsuranceRate: 0.1006 },
    { prefectureCode: '43', prefectureName: '熊本県', healthInsuranceRate: 0.1008 },
    { prefectureCode: '44', prefectureName: '大分県', healthInsuranceRate: 0.1008 },
    { prefectureCode: '45', prefectureName: '宮崎県', healthInsuranceRate: 0.0977 },
    { prefectureCode: '46', prefectureName: '鹿児島県', healthInsuranceRate: 0.1013 },
    { prefectureCode: '47', prefectureName: '沖縄県', healthInsuranceRate: 0.0944 }
  ],
} as const satisfies AssociationRateTableSet;